name: Test custom action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: ./
      with:
        private-token: ${{ secrets.PRIVATE_TOKEN }}
    - name: Test Action
      run: echo This works
